import 'package:flutter/material.dart';
import 'package:flutterapp/nikepageapp/generatedframe2widget/generated/GeneratedNikelogoWidget2.dart';
import 'package:flutterapp/nikepageapp/generatedframe2widget/generated/GeneratedSizeWidget.dart';
import 'package:flutterapp/nikepageapp/generatedframe2widget/generated/GeneratedDotsWidget.dart';
import 'package:flutterapp/nikepageapp/generatedframe2widget/generated/GeneratedAssistanceWidget.dart';
import 'package:flutterapp/nikepageapp/generatedframe2widget/generated/GeneratedBackgroundblueWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/nikepageapp/generatedframe2widget/generated/GeneratedIconsFavoriteWidget2.dart';
import 'package:flutterapp/nikepageapp/generatedframe2widget/generated/GeneratedTopWidget.dart';
import 'package:flutterapp/nikepageapp/generatedframe2widget/generated/GeneratedAddtocartWidget.dart';
import 'package:flutterapp/nikepageapp/generatedframe2widget/generated/GeneratedBackgroundwhiteWidget.dart';
import 'package:flutterapp/nikepageapp/generatedframe2widget/generated/GeneratedNikelogobigWidget.dart';
import 'package:flutterapp/nikepageapp/generatedframe2widget/generated/GeneratedTitleRatingsPriceWidget.dart';
import 'package:flutterapp/nikepageapp/generatedframe2widget/generated/GeneratedMainimageWidget2.dart';

/* Frame Frame 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(15.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(15.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(15.0),
                child: Container(
                  color: Color.fromARGB(255, 49, 59, 93),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 824.0,
                child: GeneratedBackgroundblueWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 779.0,
                child: GeneratedBackgroundwhiteWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 384.0330505371094,
                height: 32.413795471191406,
                child: GeneratedTopWidget(),
              ),
              Positioned(
                left: 358.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 320.0,
                child: GeneratedMainimageWidget2(),
              ),
              Positioned(
                left: 14.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 48.0,
                child: GeneratedNikelogoWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.0661157018320572;

                  final double height =
                      constraints.maxHeight * 0.029556651200566973;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8953168196378699,
                        y: constraints.maxHeight * 0.10837438276835851,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedIconsFavoriteWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 46.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 300.0,
                child: GeneratedNikelogobigWidget(),
              ),
              Positioned(
                left: 162.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 8.0,
                child: GeneratedDotsWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 42.47209930419922,
                child: GeneratedTitleRatingsPriceWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 513.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 79.0,
                child: GeneratedSizeWidget(),
              ),
              Positioned(
                left: 111.0,
                top: 794.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 24.0,
                child: GeneratedAssistanceWidget(),
              ),
              Positioned(
                left: 116.0,
                top: 848.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 26.0,
                child: GeneratedAddtocartWidget(),
              )
            ]),
      ),
    ));
  }
}
