import 'package:flutter/material.dart';
import 'package:flutterapp/nikepageapp/generatedframe1widget/generated/GeneratedPopularNewSaleWidget.dart';
import 'package:flutterapp/nikepageapp/generatedframe1widget/generated/GeneratedMiddlelineWidget.dart';
import 'package:flutterapp/nikepageapp/generatedframe1widget/generated/GeneratedBottomlineWidget.dart';
import 'package:flutterapp/nikepageapp/generatedframe1widget/generated/GeneratedExploreWidget.dart';
import 'package:flutterapp/nikepageapp/generatedframe1widget/generated/GeneratedProductsWidget.dart';
import 'package:flutterapp/nikepageapp/generatedframe1widget/generated/GeneratedToplineWidget.dart';
import 'package:flutterapp/nikepageapp/generatedframe1widget/generated/GeneratedVectorWidget1.dart';
import 'package:flutterapp/nikepageapp/generatedframe1widget/generated/GeneratedSearchbarWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/nikepageapp/generatedframe1widget/generated/GeneratedVectorWidget.dart';
import 'package:flutterapp/nikepageapp/generatedframe1widget/generated/GeneratedBrandWidget.dart';

/* Frame Frame 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(15.0),
      child: Container(
        width: 414.0,
        height: 896.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(15.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            //overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(15.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 150.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 32.0,
                child: GeneratedExploreWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.020460359140294763;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 8.470588684082031;

                  double percentHeight = 0.004926108356033053;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      4.413793087005615;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8670076379453503,
                        translateY:
                            constraints.maxHeight * 0.059113302401133945,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.04603687691803716;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      19.059267044067383;

                  double percentHeight = 0.022167486803872243;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      19.86206817626953;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.8542199618574502,
                        translateY: constraints.maxHeight * 0.05049261025020054,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget1())
                  ]);
                }),
              ),
              Positioned(
                left: 34.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 2.0,
                child: GeneratedBottomlineWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 50.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 2.0,
                child: GeneratedMiddlelineWidget(),
              ),
              Positioned(
                left: 45.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 2.0,
                child: GeneratedToplineWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 47.0,
                child: GeneratedSearchbarWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 169.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 30.0,
                child: GeneratedBrandWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 331.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 345.0,
                child: GeneratedPopularNewSaleWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 668.0,
                child: GeneratedProductsWidget(),
              )
            ]),
      ),
    ));
  }
}
